### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [PamBWillenz/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by PamBWillenz** [comment]
Thanks for the comment, Billy. I added the line of code in my app/views/layouts/applications.html.erb view and I think the app looks good on mobile. Everything lines up on one column. Let me know if you think so too.

**Comment by BillyMassey** [comment]
Looks Perfect!
